import 'package:flutter/material.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge3widget/generated/GeneratedWewanttoconnecthealthcareprofessionalexperiencesonmobil2.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge3widget/generated/GeneratedMaintainDoctorsprofileWidget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge3widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge3widget/generated/GeneratedNEXTWidget3.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge3widget/generated/GeneratedC13e232d5bfb467c812158c7c9ebbc3f1Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge3widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge3widget/generated/GeneratedRectangle14Widget.dart';

/* Frame Android Large - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedC13e232d5bfb467c812158c7c9ebbc3f1Widget(),
              ),
              Positioned(
                left: 36.5,
                top: 383.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 211.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 46.0,
                child: GeneratedMaintainDoctorsprofileWidget(),
              ),
              Positioned(
                left: 173.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 29.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 21.0,
                child: GeneratedNEXTWidget3(),
              ),
              Positioned(
                left: 64.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 10.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 96.0,
                child:
                    GeneratedWewanttoconnecthealthcareprofessionalexperiencesonmobil2(),
              )
            ]),
      ),
    ));
  }
}
