import 'package:flutter/material.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge1widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge1widget/generated/GeneratedTeleconsultationWidget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge1widget/generated/GeneratedEf2e6f84f79648da92e3413beddda0391Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge1widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge1widget/generated/GeneratedNEXTWidget1.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge1widget/generated/GeneratedWewanttoconnecthealthcareprofessionalexperiencesonmobil.dart';

/* Frame Android Large - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedEf2e6f84f79648da92e3413beddda0391Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 211.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 81.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 22.0,
                child: GeneratedTeleconsultationWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 96.0,
                child:
                    GeneratedWewanttoconnecthealthcareprofessionalexperiencesonmobil(),
              ),
              Positioned(
                left: 64.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 10.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 29.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 21.0,
                child: GeneratedNEXTWidget1(),
              )
            ]),
      ),
    ));
  }
}
