import 'package:flutter/material.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedSignInWidget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedUserTypeWidget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedRegisterWidget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedCreatePasswordWidget1.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/Generated49aef0dfdda2470e968a6cddeeeb97e22Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedCreatePasswordWidget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedDoyouhaveandaccountLoginWidget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge4widget/generated/GeneratedRectangle19Widget.dart';

/* Frame Android Large - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: Generated49aef0dfdda2470e968a6cddeeeb97e22Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 352.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedRegisterWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 30.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 30.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 30.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 30.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 30.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 17.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 79.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 14.0,
                child: GeneratedUserTypeWidget(),
              ),
              Positioned(
                left: 79.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 14.0,
                child: GeneratedCreatePasswordWidget(),
              ),
              Positioned(
                left: 79.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 14.0,
                child: GeneratedCreatePasswordWidget1(),
              ),
              Positioned(
                left: 155.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 15.0,
                child: GeneratedSignInWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 14.0,
                child: GeneratedDoyouhaveandaccountLoginWidget(),
              )
            ]),
      ),
    ));
  }
}
