import 'package:flutter/material.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge2widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge2widget/generated/Generated49aef0dfdda2470e968a6cddeeeb97e21Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge2widget/generated/GeneratedWewanttoconnecthealthcareprofessionalexperiencesonmobil1.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge2widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge2widget/generated/GeneratedNEXTWidget2.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge2widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge2widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/medicalappapp/generatedandroidlarge2widget/generated/GeneratedScheduleTestsWidget.dart';

/* Frame Android Large - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: Generated49aef0dfdda2470e968a6cddeeeb97e21Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 211.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 19.0,
                child: GeneratedScheduleTestsWidget(),
              ),
              Positioned(
                left: 180.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 29.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 218.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 21.0,
                child: GeneratedNEXTWidget2(),
              ),
              Positioned(
                left: 84.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 10.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 10.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 96.0,
                child:
                    GeneratedWewanttoconnecthealthcareprofessionalexperiencesonmobil1(),
              )
            ]),
      ),
    ));
  }
}
